# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mender-raspberrypi-tryboot"
BBFILE_PATTERN_meta-mender-raspberrypi-tryboot = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mender-raspberrypi-tryboot = "10"

LAYERDEPENDS_meta-mender-raspberrypi-tryboot = "core raspberrypi"
LAYERSERIES_COMPAT_meta-mender-raspberrypi-tryboot = "wrynose"

# Variable to reference this layer directory (e.g. for WKS_SEARCH_PATH)
LAYERDIR_meta-mender-raspberrypi-tryboot = "${LAYERDIR}"
