name: prepare for build

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 2 * * 6'

env:
  BUILDDIR: gh

jobs:
  prepare:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Clean up
        run: rm -fR $BUILDDIR
      - uses: actions/checkout@v4
      - name: cache metadata layers
        run: ./ci/update-repos
        env:
          LAYERCACHE: ${{ vars.PERSISTENT_DIR }}/layers
